---
title: "Awards & Honors"
toc: true
toc-location: right
toc-title: " "
---

- **2026** — Les B. Strickler Innovation in Instruction Award, American Risk and Insurance Association
- **2025** — Provost's Faculty Travel Grant, Florida State University
- **2024** — Excellence in Reviewing, *Journal of Risk and Insurance*
- **2023** — Provost's Faculty Travel Grant, Florida State University
- **2022** — *Risk Management and Insurance Review* (RMIR) Award for Best Article, American Risk and Insurance Association
- **2020** — Semi-finalist, Financial Management Association Best Paper Award in Options & Derivatives
- **2017–2018** — First Year Assistant Professor Award, Florida State University
- **2017** — Provost's Faculty Travel Grant, Florida State University
- **2016** — Harris Schlesinger Memorial Doctoral Research Award, Southern Risk and Insurance Association
- **2016** — Semi-finalist, Financial Management Association Best Paper Award in Corporate Finance
- **2016** — Hagen Family Foundation Travel Award, American Risk and Insurance Association
- **2016, 2015** — RMIN Ph.D. Student Summer Research Scholarship, University of Georgia
- **2015** — Graduate School Foreign Travel Assistance Award, University of Georgia
- **2015** — Mark Dorfman Best Ph.D. Student Paper Award, Western Risk and Insurance Association
- **2014** — Best Doctoral Student Paper Award, Southern Risk and Insurance Association
- **2014** — S.S. Huebner Doctoral Colloquium Scholar
- **2012–2017** — Knox Ph.D. Scholarship, University of Georgia
